android/src/main/kotlin/com/airship/flutter/Extensions.kt
example/android/build.gradle
gradle/wrapper/gradle-wrapper.properties
pubspec.yaml

Fixes https://github.com/urbanairship/airship-flutter/issues/9

[MOBILE-908] Fix flutter

---

android/build.gradle
android/src/main/AndroidManifest.xml
android/src/main/kotlin/com/airship/flutter/EventManager.kt
android/src/main/kotlin/com/airship/flutter/FlutterAutopilot.kt

The wrong autopilot was being used, so event handling was not working. I also noticed an error about notifying on a bg thread, so i fixed that by moving notify to the main thread with Kotlin coroutines.

Fix events on Android

---

example/lib/bloc/airship_bloc.dart
example/lib/bloc/bloc.dart
example/lib/bloc/bloc_base.dart
example/lib/main.dart
example/lib/screens/home.dart
example/lib/screens/message_center.dart
example/lib/screens/message_view.dart
example/lib/screens/named_user_add.dart
example/lib/screens/settings.dart
example/lib/screens/tag_add.dart
example/lib/widgets/notifications_enabled_button.dart
example/lib/widgets/text_add_bar.dart
ios/Classes/SwiftAirshipPlugin.swift

This reverts commit 6ca69b9b4f0b502d4eb6022676616e1bb73d7761.
This commit snuck in when I rebased the CI work to master.

Revert "[MOBILE-849] restructure without BLoC"

---

example/lib/main.dart
example/lib/screens/message_center.dart
example/lib/screens/message_view.dart
lib/src/inbox_message_view.dart

Cleans up the InboxMessageView to be more like the react-native implementation. Implements this additional widget functionality in the sample.
These changes are necessary to improve the inbox message interface on the plugin for the first release.
Manually tested.
https://urbanairship.slack.com/files/U0298VBRH/FPN4X9TBM/update_inboxmessageview.mov
This gets the timeboxed work in place, but there is some follow up work to do here related to how the plugin interfaces platform-specific web view loading:
https://urbanairship.atlassian.net/browse/MOBILE-987

[MOBILE-944] Update InboxMessageView

---

example/ios/Podfile
example/ios/Runner.xcodeproj/project.pbxproj
ios/Classes/SwiftAirshipPlugin.swift
ios/airship.podspec

Updates the iOS SDK to 12 and performs requisite migration steps.
To have the latest iOS SDK.
Ran the sample, manually tested.

[MOBILE-948] update iOS SDK to 12

---

README.md
example/ios/Podfile
example/ios/Runner.xcodeproj/project.pbxproj
example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
example/ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
example/ios/Runner/AppDelegate.swift
example/ios/Runner/Info.plist
example/lib/main.dart
example/lib/screens/home.dart
example/lib/screens/message_center.dart
example/lib/screens/message_view.dart
example/lib/screens/named_user_add.dart
example/lib/screens/settings.dart
example/lib/screens/tag_add.dart
example/pubspec.yaml
ios/Classes/AirshipInboxMessageView.swift
ios/Classes/AirshipPlugin.m
ios/Classes/Events/AirshipEvent.swift
ios/Classes/Events/AirshipNotificationResponseEvent.swift
ios/Classes/Events/AirshipPushReceivedEvent.swift
ios/Classes/SwiftAirshipPlugin.swift
ios/airship_flutter.podspec
lib/airship.dart
lib/src/airship.dart
pubspec.yaml

Updates flutter iOS version to 13.0.4
Manually tested sample

[MOBILE-1048] update iOS to 13.0.4

---

ios/Classes/SwiftAirshipPlugin.swift

fix properly mark message as read (!unread)

[MOBILE-1191] fix message read signal

---

CHANGELOG.md
example/ios/Runner.xcodeproj/project.pbxproj

Release 2.0.0

---

lib/src/airship.dart
lib/src/attribute_editor.dart
lib/src/custom_event.dart
lib/src/inbox_message_view.dart
lib/src/tag_group_editor.dart
pubspec.yaml

Formatting/config changes to improve the package health rating on pub.dev

health improvements for package

---

android/src/main/kotlin/com/airship/flutter/AirshipPlugin.kt
example/lib/screens/home.dart
example/lib/screens/message_center.dart
example/lib/screens/message_view.dart
example/lib/screens/named_user_add.dart
example/lib/screens/settings.dart
example/lib/screens/tag_add.dart
ios/Classes/SwiftAirshipPlugin.swift
lib/src/airship.dart

Add screen tracking to flutter.
Ran the app and verified that the trackScreen method is called.

[MOBILE-1225] Add screen tracking

---

README.md
ios/Classes/SwiftAirshipPlugin.swift
ios/airship_flutter.podspec
lib/src/attribute_editor.dart
pubspec.yaml

Updates flutter iOS version to 13.1
Adds number attribute support
Manually tested the sample app

[MOBILE-1274] Update iOS to 13.1

---

android/build.gradle
android/src/main/kotlin/com/airship/flutter/AirshipPlugin.kt
example/android/build.gradle
example/android/gradle/wrapper/gradle-wrapper.properties

Updates flutter Android version to 12.2
Adds number attribute support
Manual tests in the sample app

[MOBILE-1273] Update Android to 12.2

---

CHANGELOG.md
DEV_README.md
android/src/main/kotlin/com/airship/flutter/AirshipPluginVersion.kt
ios/Classes/AirshipPluginVersion.swift

Release 2.1.0
To happen after [message view changes](https://urbanairship.atlassian.net/browse/MOBILE-987) are in.

Release 2.1.0

---

.github/workflows/release.yml
CHANGELOG.md
scripts/check_verison.sh

Adds creating a github release during our release flow. Reformats the changelog to make it easier to pull the release notes. Simplified the release workflow and added a check version step.

[MOBILE-1345] Add github release

---

CHANGELOG.md
DEV_README.md
README.md
android/src/main/kotlin/com/airship/flutter/AirshipPluginVersion.kt
ios/Classes/AirshipPluginVersion.swift
ios/airship_flutter.podspec

Release 3.0.1

---

android/build.gradle
android/src/main/kotlin/com/airship/flutter/AirshipPlugin.kt
android/src/main/kotlin/com/airship/flutter/Extensions.kt
android/src/main/kotlin/com/airship/flutter/FlutterAutopilot.kt
example/android/build.gradle

Updates to latest Android SDK.
Needed for new features and fixes issues.
Sample app.

[MOBILE-1536] Update Android SDK to 13.1.0

---

CHANGELOG.md
DEV_README.md
README.md
android/src/main/kotlin/com/airship/flutter/AirshipPluginVersion.kt
ios/Classes/AirshipPluginVersion.swift
ios/airship_flutter.podspec
pubspec.yaml

Release 3.0.2

---

lib/src/attribute_editor.dart
pubspec.yaml

Add date attributes to flutter.
To allow customers using flutter to use the feature.
Manual tests.

[MOBILE-1534] Add date attributes

---

android/src/main/kotlin/com/airship/flutter/AirshipPlugin.kt
ios/Classes/SwiftAirshipPlugin.swift
lib/src/airship_flutter.dart

Add named user attribute support to Flutter.
To allow customers using flutter to use the feature.
Manual tests.

[MOBILE-1565] Add named user attributes

---

android/build.gradle

Update the Android SDK used by our Flutter plugin
To stay updated
Launching the app, testing basic functionalities of Airship, and checking that the correct version is loaded.

[MOBILE-1769] Updating Airship SDK to 13.3.1

---

.github/workflows/release.yml
.gitignore
CHANGELOG.md
DEV_README.md
android/build.gradle
android/src/main/kotlin/com/airship/flutter/AirshipPluginVersion.kt
example/ios/Podfile
example/ios/Runner.xcodeproj/project.pbxproj
example/ios/Runner/Info.plist
example/ios/Runner/Runner.entitlements
ios/Classes/AirshipPluginVersion.swift
ios/airship_flutter.podspec
pubspec.yaml

Update native SDKs to latest versions and create release.
Some new Flutter features to roll out, plus a few native SDK fixes.
Local CI. Received push on both iOS and Android.
- I fixed a small error in the DEV_README
- I had to make changes to the iOS example project to get it to run and receive a push
- I made a fix to the docs build that will hopefully publish the docs as we expect them.

[MOBILE-1819] Update native SDKs and release 8.1.0

---

.github/workflows/ci.yml
.github/workflows/release.yml
CHANGELOG.md
DEV_README.md
README.md
android/build.gradle
android/src/main/kotlin/com/airship/flutter/AirshipPlugin.kt
android/src/main/kotlin/com/airship/flutter/AirshipPluginVersion.kt
ios/Classes/AirshipPluginVersion.swift
ios/Classes/SwiftAirshipPlugin.swift
ios/airship_flutter.podspec
pubspec.yaml

Update Android SDK to 14.0.0 and iOS SDK to 14.1.1
Support major SDK releases
Tested the sample app

[MOBILE-1899] Update Android to 14.0 and iOS to 14.1.1

---

.github/workflows/ci.yml
.github/workflows/release.yml
CHANGELOG.md
android/build.gradle
android/src/main/kotlin/com/airship/flutter/AirshipPlugin.kt
android/src/main/kotlin/com/airship/flutter/AirshipPluginVersion.kt
android/src/main/kotlin/com/airship/flutter/EventManager.kt
ios/Classes/AirshipPluginVersion.swift
ios/airship_flutter.podspec
pubspec.yaml

Updates latest SDKs and fixes events on Android.

Release 4.0.1

---

.github/workflows/ci.yml
.github/workflows/release.yml
android/src/main/kotlin/com/airship/flutter/AirshipPlugin.kt
example/lib/screens/message_center.dart
example/pubspec.yaml
ios/Classes/SwiftAirshipPlugin.swift
lib/src/airship_flutter.dart

These changes should allow customers using the flutter SDK to manually refresh the inbox. Currently refreshes only happen when opening the app or when a push is received with a message center message.
A customer wants to be able to refresh the inbox inside the app.
https://urbanairship.atlassian.net/browse/CUSTENG-3584
I tested the changes on an android device.
**I have not tested the changes on iOS**, I could use some help testing my iOS changes out!
iOS still needs to be tested. I'm not 100% sure I called the correct iOS method.

[CUSTENG-3584] Add support for refreshing message center messages in flutter

---

android/build.gradle
ios/airship_flutter.podspec

Updates the SDK versions
Keep the Flutter plugin up to date with Airship SDKs
Build and launch

[MOBILE-2138] Update SDK versions

---

.github/workflows/ci.yml
.github/workflows/release.yml
android/build.gradle
example/ios/Runner.xcodeproj/project.pbxproj
example/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
example/lib/screens/message_center.dart
example/lib/screens/tag_add.dart
example/pubspec.yaml
ios/airship_flutter.podspec
lib/src/attribute_editor.dart
lib/src/tag_group_editor.dart
pubspec.yaml
scripts/docs.sh

Make sure our flutter plugin is compatible with Flutter 2
Make our flutter plugin compatible with Flutter 2
Build and run
I had an issue on building the docs. I had to install dartdoc global package and use it instead of the one that is already in the dart sdk.

[MOBILE-2137] Update to Flutter 2

---

CHANGELOG.md
android/src/main/kotlin/com/airship/flutter/AirshipPluginVersion.kt
ios/Classes/AirshipPluginVersion.swift
ios/airship_flutter.podspec
pubspec.yaml

Update flutter version to 4.2.0. This supports Flutter 2 but the minimum requirements remain the same.
To release our flutter module 4.2.0
Build and run the sample

[MOBILE-2139] Release 4.2.0

---

lib/src/airship_flutter.dart
lib/src/attribute_editor.dart
lib/src/custom_event.dart
lib/src/inbox_message_view.dart
lib/src/tag_group_editor.dart
pubspec.yaml

Migrate the plugin to use non-nullable types and Add null safety annotations.
Make the plugin support null safety.
Build, run, send some message in the message center and check tags.
But I think some QA tests would be valuable just in case.
I used the migration tool then checked and manually adapted the suggestions.

[MOBILE-2195] Add null safety annotations

---

CHANGELOG.md
android/build.gradle
android/src/main/kotlin/com/airship/flutter/AirshipPluginVersion.kt
example/android/app/build.gradle
ios/Classes/AirshipPluginVersion.swift
ios/airship_flutter.podspec
pubspec.yaml

Update SDKs version
For the release 4.3.0
Build and run

[MOBILE-2330] Release 4.3.0

---

ios/Classes/SwiftAirshipPlugin.swift
lib/src/airship_flutter.dart

Exposes resetBadge, setBadge, setAutoBadgeEnabled, isAutobadgeEnabled.
Tested on iOS sample app.

[MOBILE-2426] Expose badge methods

---

CHANGELOG.md
android/src/main/kotlin/com/airship/flutter/AirshipPluginVersion.kt
ios/Classes/AirshipPluginVersion.swift
ios/airship_flutter.podspec

Release 5.0.1

---

ios/Classes/AirshipEventManager.swift
lib/src/airship_flutter.dart

Make notificationId nullable and fix a very weird crash where ``event.data`` where nil but goes into the if anyway and then crash on ``event.data!``
Try to fix crashs
I don't reproduce the customer crash so I'm not 100% sure how to fix it properly
Also deeplink does not work and I'm digging to find out why it's not.
The other weird crash, I just tested it with a push with deeplink
I had a very weird crash and also deeplink does not work and I'm digging to find out why it's not.
Beside this, I can't reproduce the customer crash so I'm not 100% sure how to fix it properly.

[MOBILE-2700] Try to fix crashs

---

ios/Classes/SwiftAirshipPlugin.swift

onShowInbox and onShowInboxMessage was not working for iOS

Fix onShowInbox and onShowInboxMessage for iOS

---

CHANGELOG.md
android/build.gradle
android/src/main/kotlin/com/airship/flutter/AirshipPluginVersion.kt
ios/Classes/AirshipPluginVersion.swift
ios/airship_flutter.podspec

Prepare release 5.1.1
Keep up to date
iOS OK, android OK

[MOBILE-2821] prepare release 5.1.1

---

example/lib/main.dart
example/lib/screens/preference_center.dart
example/pubspec.yaml
lib/airship_flutter.dart

Add custom preference center screen

Add custom preference center

---

lib/src/airship_flutter.dart
lib/src/attribute_editor.dart
lib/src/channel_scope.dart
lib/src/custom_event.dart
lib/src/inbox_message_view.dart
lib/src/preference_center_config.dart
lib/src/scoped_subscription_list_editor.dart
lib/src/subscription_list_editor.dart
lib/src/tag_group_editor.dart

Document public flutter APIs.
So the flutter docs have better context
Manual test with dartdoc

[MOBILE-2950] Document public flutter APIs

---

CHANGELOG.md
README.md
android/build.gradle
android/src/main/kotlin/com/airship/flutter/AirshipBackgroundExecutor.kt
android/src/main/kotlin/com/airship/flutter/AirshipPluginVersion.kt
ios/Classes/AirshipInboxMessageView.swift
ios/Classes/AirshipPluginVersion.swift
ios/airship_flutter.podspec
pubspec.yaml

Cherry-pick the two fixes we did on main
To release a patch version from 5.5.0
Build and run

[MOBILE-3160] patch version 5.5.1

---

CHANGELOG.md
README.md
android/build.gradle
android/src/main/kotlin/com/airship/flutter/AirshipPluginVersion.kt
ios/Classes/AirshipPluginVersion.swift
ios/airship_flutter.podspec
pubspec.yaml

Update to android SDK 16.7.0 and iOS SDK 16.9.0
Update to latest SDKs
Build and run

[MOBILE-3160] Update to latest SDKs

---

ios/Classes/AirshipEventHandler.swift
ios/Classes/AirshipInboxMessageView.swift

Inbox messages don’t seem to display properly when sent through a push. The message list is not refreshed and so, when trying to display, we can’t retrieve the message since it’s not in the outdated message list.

[MOBILE-3330] Fix inbox message display

---

.github/workflows/ci.yml
.github/workflows/release.yml
CHANGELOG.md
README.md
android/build.gradle
android/src/main/kotlin/com/airship/flutter/AirshipPluginVersion.kt
ios/Classes/AirshipPluginVersion.swift
ios/airship_flutter.podspec
pubspec.yaml

Release 6.2.0. Bumps SDK versions only

Release 6.2.0

---

CHANGELOG.md
README.md
ios/Classes/AirshipPluginVersion.swift
ios/airship_flutter.podspec
pubspec.yaml

Release 6.2.1

---

CHANGELOG.md
README.md
ios/Classes/AirshipPluginVersion.swift
ios/airship_flutter.podspec
lib/src/airship_flutter.dart
pubspec.yaml

Merge upstream changes from main into this workaround branch
Since we are currently relying on this branch in our production builds, it would be great if we could benefit from the fixes introduced in Airship 16.10.5
Should be fine since the changes are already in main

Merge main into workaround-bg-push

---

android/src/main/kotlin/com/airship/flutter/Extensions.kt
ios/Classes/Events/AirshipNotificationResponseEvent.swift
ios/Classes/Events/AirshipPushReceivedEvent.swift
ios/Classes/PushUtils.swift
ios/Classes/SwiftAirshipPlugin.swift

Fixes getActiveNotifications by returning the proper JSON expected in the dart layer. Also added a fix on missing subtitle on Android for the push received event. I didnt bother trying to consolidate the various push parsing on Android since we will be switching over to the proxy shortly.

[GH-155] Fix getActiveNotifications on iOS

---

CHANGELOG.md
README.md
android/build.gradle
android/src/main/kotlin/com/airship/flutter/AirshipPluginVersion.kt
example/ios/Flutter/AppFrameworkInfo.plist
example/ios/Runner.xcodeproj/project.pbxproj
example/ios/Runner/Info.plist
ios/Classes/AirshipPluginVersion.swift
ios/Classes/SwiftAirshipPlugin.swift
ios/airship_flutter.podspec
pubspec.yaml

Prepare a patch release to fix `editContactSubscriptionLists` methods on iOS.

Prepare 16.2.3

---

android/build.gradle
android/src/main/kotlin/com/airship/flutter/AirshipPlugin.kt
ios/Classes/SwiftAirshipPlugin.swift
ios/airship_flutter.podspec
lib/airship_flutter.dart
lib/src/airship_channel.dart
lib/src/tag_editor.dart

Add editTags method
To keep updated
I tested this with a local version of the proxy on android and iOS

[MOBILE-3854] Add editTags method

---

.github/workflows/ci.yml
.github/workflows/release.yml
CHANGELOG.md
android/build.gradle
android/src/main/kotlin/com/airship/flutter/AirshipPlugin.kt
android/src/main/kotlin/com/airship/flutter/AirshipPluginVersion.kt
android/src/main/kotlin/com/airship/flutter/Extensions.kt
example/lib/main.dart
ios/Classes/AirshipPluginVersion.swift
ios/Classes/SwiftAirshipPlugin.swift
ios/airship_flutter.podspec
lib/src/airship_feature_flag_manager.dart
pubspec.yaml

Still need to verify the changes

Release 7.2.0

---

.github/workflows/release.yml

Fixes releaseDoc job in release workflow by setting up gcloud to get gsutil installed.

setup gcloud to get gsutil installed

---

.github/CODEOWNERS
CHANGELOG.md
android/build.gradle
android/src/main/kotlin/com/airship/flutter/AirshipPluginVersion.kt
example/lib/screens/tag_add.dart
ios/Classes/AirshipPluginVersion.swift
ios/airship_flutter.podspec
pubspec.yaml

Minor release that updates the Android SDK to 17.8.1 and iOS SDK to 18.2.0
- Updated Android SDK to 17.8.1.
- Updated iOS SDK to 18.2.0.
---
Also updated CODEOWNERS to `uariship/mobile`

Release 7.4.0

---

CHANGELOG.md
android/src/main/kotlin/com/airship/flutter/AirshipPluginVersion.kt
ios/Classes/AirshipPluginVersion.swift
ios/airship_flutter.podspec
pubspec.yaml

Release 7.7.1

---

CHANGELOG.md
android/src/main/kotlin/com/airship/flutter/AirshipPluginVersion.kt
ios/Classes/AirshipPluginVersion.swift
ios/airship_flutter.podspec
pubspec.yaml

Release 7.8.0

---

CHANGELOG.md
android/src/main/kotlin/com/airship/flutter/AirshipPluginVersion.kt
ios/Classes/AirshipPluginVersion.swift
ios/Classes/SwiftAirshipPlugin.swift
ios/airship_flutter.podspec
lib/src/airship_in_app.dart
pubspec.yaml

- Bring back removed in-app methods
- Split guard statement
- Remove duplicate in changelog
To fix things
manual test with sample

Prepare patch release 7.8.1

---

android/build.gradle

Uses our framework proxy-hms to add HMS support
To add HMS support to flutter
Finally being able to receive push on the sample app from our HMS Provider on a Huawei device from the Huawei cloud debugging.

Add HMS support

---

CHANGELOG.md
android/build.gradle
android/src/main/kotlin/com/airship/flutter/AirshipPluginVersion.kt
ios/Classes/AirshipPluginVersion.swift
ios/airship_flutter.podspec
pubspec.yaml

Release 8.0.2

---

CHANGELOG.md
android/build.gradle
android/src/main/kotlin/com/airship/flutter/AirshipPluginVersion.kt
ios/Classes/AirshipPluginVersion.swift
ios/airship_flutter.podspec
pubspec.yaml

Release 8.0.3

---

CHANGELOG.md
android/build.gradle
android/src/main/kotlin/com/airship/flutter/AirshipPluginVersion.kt
ios/Classes/AirshipPluginVersion.swift
ios/airship_flutter.podspec
pubspec.yaml

Release 8.0.4

---

CHANGELOG.md
android/src/main/kotlin/com/airship/flutter/AirshipBackgroundExecutor.kt
android/src/main/kotlin/com/airship/flutter/AirshipPlugin.kt
android/src/main/kotlin/com/airship/flutter/AirshipPluginVersion.kt
example/android/app/src/main/AndroidManifest.xml
ios/Classes/AirshipPluginVersion.swift
ios/airship_flutter.podspec
pubspec.yaml

Release 9.0.0

---

.github/workflows/release.yml
CHANGELOG.md
android/build.gradle
android/src/main/kotlin/com/airship/flutter/AirshipPluginVersion.kt
ios/Classes/AirshipPluginVersion.swift
ios/airship_flutter.podspec
pubspec.yaml

Release 9.0.1

---

CHANGELOG.md
android/build.gradle
android/src/main/kotlin/com/airship/flutter/AirshipPluginVersion.kt
ios/Classes/AirshipPluginVersion.swift
ios/airship_flutter.podspec
pubspec.yaml

Release 9.1.0

---

.github/workflows/update.yml
scripts/update_changelog.sh
scripts/update_proxy.sh

Release prep workflow and scripts

Add release preparation action and scripts

---

CHANGELOG.md
android/build.gradle
android/src/main/kotlin/com/airship/flutter/AirshipPluginVersion.kt
ios/airship_flutter.podspec
ios/airship_flutter/Sources/airship_flutter/AirshipPluginVersion.swift
pubspec.yaml

Release 10.2.0

---

example/lib/main.dart
lib/src/airship_config.dart

Fix android logging
