urbanairship/airship-flutter

android/src/main/kotlin/com/airship/flutter/AirshipPlugin.kt
android/src/main/kotlin/com/airship/flutter/Extensions.kt
android/src/main/kotlin/com/airship/flutter/FlutterAutopilot.kt
android/src/main/kotlin/com/airship/flutter/Utils.kt
ios/Classes/SwiftAirshipPlugin.swift
lib/src/airship.dart

Adds notification management API to flutter implementation 
Allow developers to manage active notifications 
Added method calls to airship_bloc.dart 
`Airship.activeNotifications.then((val) {
debugPrint('Active notifications: $val');
});` 
then sent a push notification and used the debugger on iOS and Android to check if the API works as expected
I was trying to port the React Native implementation but am not too sure about the activeNotifications Android implementation and what the payload should contain

[MOBILE-584] Add notification management

---

example/lib/main.dart
example/lib/screens/message_center.dart
example/lib/screens/message_view.dart

These changes allow onShowInboxMessage events to be correctly handled and display a custom message view instead of the OOTB message view.
To prevent the UI from transitioning to the OOTB message view and inbox when opening a message center message from a push.
Manually tested
https://urbanairship.slack.com/archives/G0B2N1MGX/p1572277892077200

[MOBILE-945] fix Android launching OOTB Message Center in sample

---

android/src/main/kotlin/com/airship/flutter/FlutterAutopilot.kt
ios/Classes/SwiftAirshipPlugin.swift

Add custom notification button support
To allow for automatic loading of custom notification button categories
Created the UACustomNotificationCategories plist/xml file containing custom categories.
Tested manually on both iOS and Android.

[MOBILE-594] Notification button support

---

android/src/main/kotlin/com/airship/flutter/AirshipPlugin.kt
ios/Classes/SwiftAirshipPlugin.swift
lib/src/airship.dart

It exposes paused property for In-App automation through getter and setter.
They are necessary to support In-App automation.
I didn't verify changes. I don't know how to do it on Flutter.
None
None

Mobile 587 add in app automation support

---

CHANGELOG.md
README.md
pubspec.yaml

Updates the flutter plugin to prepare for publish.
To push the plugin to pub.dev.
Ran publish dry run via
`flutter pub pub publish --dry-run`

[MOBILE-946] prep flutter plugin for initial publish

---

android/src/main/kotlin/com/airship/flutter/AirshipPlugin.kt
android/src/main/kotlin/com/airship/flutter/FlutterAutopilot.kt
ios/Classes/SwiftAirshipPlugin.swift
lib/src/airship.dart

In order for the delay channel creation feature to work, we need to expose the enable channel creation call in flutter. This adds it.
Customer request.
Manually verified the enableChannelCreation call is able to be triggered.

MOBILE-1199: Delayed channel creation support

---

android/src/main/kotlin/com/airship/flutter/AirshipPlugin.kt
ios/Classes/SwiftAirshipPlugin.swift
lib/src/airship.dart

Add data collection and push token collection enablement to airship-flutter
To allow customers using the flutter integration to use these features.
Manually tested that the switching results in the correct method calls.

[MOBILE-1272] add data collection enabled flag to flutter

---

.github/workflows/release.yml

Adds flutter deploy job to github actions.
To allow flutter deploys from github actions.
The build/ios/android jobs are all verified and currently in use. Not able to verify publish and finish jobs yet, will have to run them. Verified pub-dev credentials and slack hook.

[MOBILE-1286] Move Flutter deploy to Github Actions

---

example/lib/screens/settings.dart
example/lib/screens/tag_add.dart

In testing an issue, saw that some state was failing to update in the example. This fixes this state change issue by calling update state at the appropriate times.
Make the sample properly display state.
Manual tests
This gif itself has a low frame rate - the frame rate is fine in the app:

[MOBILE-1545] fix example to properly show state changes

---

ios/Classes/SwiftAirshipPlugin.swift
ios/airship_flutter.podspec

Updates to latest iOS SDK to fix issue for https://github.com/urbanairship/airship-flutter/pull/47. 
Custom event property methods could be updated to support any JSON on the dart side but we will do that in a separate PR after Android SDK is updated.

[MOBILE-1535] Update iOS SDK to 13.3.0

---

lib/src/custom_event.dart

Update the custom event property to `setProperties(Map<String, dynamic>)` and `addProperty(String, dyamic)`. 
Using the example app.
example of code: 
```
CustomEvent event = CustomEvent("Event name", 123);
event.addProperty("test", true);
event.addProperty("First name", true);
event.addProperty("Last name", "lastname");
```
```
var properties = new Map<String, dynamic>();
properties["First name"] = "Me";
properties["age"] = 30;
event.setProperties(properties);
Airship.addEvent(event);
```

[MOBILE-1563] - Remove property restrictions for  custom events in flutter

---

ios/airship_flutter.podspec

Updating the Flutter iOS SDK used to version 13.5.2
To stay updated
Launching the app, testing basic functionalities of Airship, and checking that the correct version is loaded.

[MOBILE-1770] Update Flutter to iOS SDK Version 13.5.2

---

DEV_README.md
example/lib/main.dart

Fix exception in the example app.
Example app needs to work.
Launched app successfully.
Example app was throwing the following exception on launch: 
```
ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
If you’re running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
```
Simply following the instructions fixed the problem.

Fix exception in example app.

---

pubspec.yaml

https://github.com/urbanairship/airship-flutter/issues/64
ℹ  Fix the intl version to make it useable for the latest Flutter stable channel
ℹ  Can't use the latest flutter stable or an airship version below 3.1.0 because of XCode 12
ℹ  Please use an application with intl package and the Xcode version 12 to test this fixes.
ℹ  --
ℹ  --

fix intl version for issue #64

---

CHANGELOG.md
android/src/main/kotlin/com/airship/flutter/AirshipPluginVersion.kt
example/pubspec.yaml
ios/Classes/AirshipPluginVersion.swift
ios/airship_flutter.podspec
pubspec.yaml

Update the iOS SDK to 14.2.2
To keep the flutter plugin up to date
Build and execute
Apparently, the last version of pull to refresh generates somes issues during the build, so I used the previous one.
See this for more information: peng8350/flutter_pulltorefresh#424

[MOBILE-2060] Update iOS SDK version to 14.2.2

---

CHANGELOG.md
scripts/docs.sh

I updated the iOS SDK version with our last version but I noticed I forgot to update it in the changelog.
I also fixed my mess in the docs script

[MOBILE-2139] Update iOS SDK version in changelog

---

pubspec.yaml

Add repo and issues links to [`pub.dev/packages/airship_flutter`](https://pub.dev/packages/airship_flutter)
It's difficult to find the repository for the package on pub.dev

Add repository and issue tracker to the pubspec

---

.github/workflows/release.yml

Updates to the new modular GCP setup action.
So that deploys continue working.
Doing it live, but tested the new action in a private repo and it installed the GCP CLI utils without issue.

[MOBILE-2438] Update setup-cloud action in release workflow

---

android/build.gradle
android/src/main/kotlin/com/airship/flutter/AirshipPlugin.kt
android/src/main/kotlin/com/airship/flutter/ConfigManager.kt
android/src/main/kotlin/com/airship/flutter/EventManager.kt
android/src/main/kotlin/com/airship/flutter/Extensions.kt
android/src/main/kotlin/com/airship/flutter/FlutterAutopilot.kt
example/android/app/build.gradle
example/android/app/src/main/AndroidManifest.xml
example/android/build.gradle
example/android/gradle.properties
example/ios/Flutter/AppFrameworkInfo.plist
example/ios/Runner.xcodeproj/project.pbxproj
example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
ios/Classes/AirshipAutopilot.swift
ios/Classes/AirshipEventHandler.swift
ios/Classes/AirshipEventManager.swift
ios/Classes/AirshipInboxMessageView.swift
ios/Classes/AirshipPlugin.m
ios/Classes/PluginConfig.swift
ios/Classes/SwiftAirshipPlugin.swift
lib/src/airship_flutter.dart

Adds a new `takeOff` method that you can pass the app key and secret into.  The credentials are combined with the config in the plist/properties file. Release/Debug credentials set in the config will take precedents, so in order to use this the app has to remove appkey/secret from the config before calling takeOff. Updates to the config after will not take until the next app init.
I tested on both iOS and Android using the sample App. I launched the app with normal config to see that it worked. I then removed the app key/secret and assigned it to a button click. I navigated the app to make sure we dont have any crashes, then I pressed the takeOff button to verify everything works. Next app launch everything worked before the takeOff button.

GH-115: Add support for takeOff directly from dart

---

android/src/main/kotlin/com/airship/flutter/AirshipPlugin.kt
ios/Classes/SwiftAirshipPlugin.swift
lib/src/airship_flutter.dart

On iOS we were only clearing named user (contact reset) when the value is null and not checking for empty. On Android it was using the deprecated named user APIs so it was fine, but I updated to also use contact so its doing the proper check now as well.

[GH-120] Allow null or empty string to clear named user

---

.github/workflows/release.yml

Live fix the flutter release actions.
Seems pub is no longer a global command as it used to be.
Makes possible to run `flutter pub publish -f` in the release action
`pub` is no longer a global command as it may have been in the previous version.
prefixing it with flutter/dart is necessary e.i `flutter pub publish`
`flutter pub publish --dry-run`

fix flutter plugin release ci.

---

CHANGELOG.md
README.md
android/src/main/kotlin/com/airship/flutter/AirshipBackgroundExecutor.kt
android/src/main/kotlin/com/airship/flutter/AirshipPluginVersion.kt
ios/Classes/AirshipPluginVersion.swift
ios/airship_flutter.podspec
pubspec.yaml

Patch version to fix silent push in background.
I updated the notification arg we send to the background message isolate callback.
To fix the background message handler for silent pushes
manual tests with a silent push

[MOBILE-3171] Patch to fix silent push in background

---

ios/Classes/AirshipInboxMessageView.swift

Return to avoid multiple decisionHandler calls
To fix a crash
Manual tests and debug

[MOBILE-3182] Return to avoid crash on multiple decisionHandler calls

---

lib/src/airship_flutter.dart

With Flutter 3.3 you have to annotate methods that will be used from native code with `@pragma('vm:entry-point')`. I've added this annotation to `_backgroundMessageIsolateCallback()`.
When you use this plugin with Flutter 3.3 you will get the following error message with release builds.
```
E/flutter (27564): [ERROR:flutter/shell/common/shell.cc(93)] Dart Error: Dart_LookupLibrary:library 'package:airship_flutter/src/airship_flutter.dart' not found.
```
This happens because the compiler does not know that you call this function from native code so it removes it. 
Build the example app as release with Flutter 3.3 and view the logs. The error message will be gone.
- https://github.com/dart-lang/sdk/blob/master/runtime/docs/compiler/aot/entry_point_pragma.md
- …

Annotate background message handler with @pragma('vm:entry-point')

---

README.md

The pull request adds the information about EU Cloud Site to the Readme (source: docs.airship.com).
It's necessary for users from the EU to add this to their config. The logs didn't tell me why my channel ID was null. Important details like this should not only be in the documentation but also in the Readme.

Include cloud site info in README.md

---

ios/Classes/AirshipEventHandler.swift

Modifies the registration delegate `apnsRegistrationSucceeded` func signature to match the current one in the iOS SDK.

[MOBILE-3410] Fix registration delegate callback

---

ios/Classes/AirshipEventHandler.swift

Adds a listener for channel creation instead of only doing the registration event on token registration.

[GH-152] Fix channel registration event when channel is created on iOS

---

.github/workflows/release.yml
scripts/docs.sh

* Tweaks the `docs.sh` script to only build and package docs into `/docs/${VERSION}.tar.gz`. We no longer need it to do the upload, as there's a new action that makes it easy to do from the workflow.
* Updates the workflow to:
* Use the latest GCP auth and upload actions (should fix the python issue that prevented the docs from uploading in previous releases)
* Migrate from `::set-output` to `$GITHUB_OUTPUT` to fix warnings
Doc upload step broke and we had some other warnings that needed fixing.
Verified the script changes manually, but we'll have to run the release workflow to know for sure.
The GCP action changes were basically identical to changes already made in the Android repo, so I'm not expecting any issues.

[MOBILE-3542] Fix doc upload and misc warnings in release workflow

---

ios/Classes/SwiftAirshipPlugin.swift

Matches custom event value behaviour on iOS to the one on Android (allows null value to be set).

Mobile 3550 

---

android/build.gradle
example/lib/screens/preference_center.dart
lib/src/preference_center_config.dart

Following a customer issue where the Preference center at Contact level does not work properly
Before, when unsubscribing to a list, at a contact level, it only put an empty scope list as value, but the subscriptionId was still in the list.
Since the switch button was checking if the subscriptionId is in the list, the switch stayed enabled
So I made a change to remove the subscriptionId if you unsubscribe to it.
I also added a "app" scope by default, because the SDK does not subscribe if there is no scope in the Contact subscriptions.
To fix the Preference Center in Flutter
By running the sample app, and using the "preference_center" id, that is contact level

[MOBILE-3551] Remove the contact subscription to fix the switch state

---

CHANGELOG.md
README.md
android/src/main/kotlin/com/airship/flutter/AirshipPluginVersion.kt
ios/Classes/AirshipPluginVersion.swift
ios/airship_flutter.podspec
pubspec.yaml

Patch release that updates the Android SDK to 16.9.2 and fixes an issue with contact subscriptions 
in the example Preference Center.
- Updated Android SDK to 16.9.2
- Fixed an issue with contact-level subscription lists in the example Preference Center.

Release 6.3.1

---

CHANGELOG.md
README.md
pubspec.yaml

Bump the minimal version of intl to >=0.18.0 make it compatible SDK 3.10.0
So a customer can use Flutter SDK 3.10.0
By running the sample app and testing it

Patch release 6.3.2

---

CHANGELOG.md
android/build.gradle
ios/Classes/SwiftAirshipPlugin.swift
ios/airship_flutter.podspec
pubspec.yaml

Adds the `Airship.push.iOS.resetBadge` that got unfortunately removed, and changes the versions to prepare for hotfix release
To have all the methods available
Running the sample app and testing

Release 7.10

---

lib/src/airship_events.dart
lib/src/airship_message_center.dart

Following an issue where the event stream wasn't properly parsed : https://github.com/urbanairship/airship-flutter/issues/186
Tested it with a push and message center action, and works properly now.

Fix event exception

---

CHANGELOG.md
pubspec.yaml

Patch release that fixes an exception occuring while listening to the `Airship.messageCenter.onDisplay` event
- Fixed an error with Airship.messageCenter.onDisplay

Release 7.1.2

---

.github/workflows/release.yml
android/build.gradle

- Fixes a typo in the DEVELOPER_DIR to address the following:
```
Cannot find "xcodebuild". Xcode 13 or greater is required to develop for iOS.
Encountered error while building for device.
```
- Updates Kotlin to address the following:
```
e: /Users/runner/work/airship-flutter/airship-flutter/example/build/airship_flutter/.transforms/5311bca21027a3e31527fed45aa0e1e9/transformed/out/jars/classes.jar!/META-INF/airship_flutter_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1.
e: /Users/runner/.gradle/caches/transforms-3/fe9e40ada0c61d8faedb147178a80e05/transformed/jetified-airship-framework-proxy-5.0.2/jars/classes.jar!/META-INF/airship-framework-proxy_release.kotlin_module: Module was …
```

Fix release ci

---

.github/CODEOWNERS
CHANGELOG.md
android/build.gradle
android/src/main/kotlin/com/airship/flutter/AirshipPlugin.kt
android/src/main/kotlin/com/airship/flutter/AirshipPluginVersion.kt
ios/Classes/AirshipPluginVersion.swift
ios/Classes/SwiftAirshipPlugin.swift
ios/airship_flutter.podspec
lib/src/airship_contact.dart
pubspec.yaml

Minor release that updates the iOS SDK to 17.7.0 and Android SDK to 17.6.0 and adds support for notifying the contact of a remote login.
- Updated iOS SDK to 17.7.0
- Updated Android SDK to 17.6.0
- Added `Airship.contactManager.notifyRemoteLogin()` method to notify contact of remote login
🚀
Set breakpoints on the new notifyRemoteLogin method and ensured these breakpoints were hit.

Release 7.3.0

---

CHANGELOG.md
android/build.gradle
android/src/main/AndroidManifest.xml
android/src/main/kotlin/com/airship/flutter/AirshipPluginVersion.kt
ios/Classes/AirshipPluginVersion.swift
ios/airship_flutter.podspec
pubspec.yaml

Add a namespace to our flutter module
To fix a build issue due to the use of gradle 8.
Reproduced on the flutter sample.

[MOBILE-4148] Fix gradle 8 build issue

---

android/build.gradle

I've updated the sourceCompatibility and targetCompatibility for Java in the build.gradle file.
These changes are necessary since Flutter has updated its version and we have a warning in the console. Without this change, we can't update the configuration.
```txt
You are applying Flutter's app_plugin_loader Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/go/flutter-gradle-plugin-apply
You are applying Flutter's main Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: …
```

Add compileOptions to fix new flutter release warning

---

.github/workflows/ci.yml
.github/workflows/release.yml
CHANGELOG.md
android/build.gradle
android/src/main/kotlin/com/airship/flutter/AirshipPluginVersion.kt
example/android/app/build.gradle
example/android/build.gradle
example/android/settings.gradle
example/lib/main.dart
ios/Classes/AirshipPluginVersion.swift
ios/airship_flutter.podspec
pubspec.yaml
scripts/run_ci_tasks.sh

- Adds kotlin specification to android build config and migrates away from build script to resolve warnings
- Updates some small things in the UI like the tab bar height being outside safe area in ios
Keep things up to date and test some changes to android builds
Manually tested both samples
https://github.com/urbanairship/airship-flutter/assets/2199816/ba84fbca-fb33-4ffe-b033-e0024519dd2e

Release 7.5.0

---

ios/Classes/AirshipInboxMessageView.swift

Attempts a refresh when launching an MC message from a push. Similar to what we do in the react-native plugin.
To resolve some preventable message open failures.
Tested with and without the change launching the message center from an MC-containing push.

Fix message center message retrieval when launched from mc push

---

CHANGELOG.md
android/build.gradle
android/src/main/kotlin/com/airship/flutter/AirshipPluginVersion.kt
ios/Classes/AirshipAutopilot.swift
ios/Classes/AirshipPluginVersion.swift
ios/airship_flutter.podspec
lib/src/airship_config.dart
lib/src/airship_embedded_view.dart
lib/src/airship_feature_flag_manager.dart
lib/src/airship_live_update_manager.dart
lib/src/airship_push.dart
lib/src/custom_event.dart
lib/src/inbox_message.dart
lib/src/inbox_message_view.dart
lib/src/live_activity.dart
lib/src/push_notification_status.dart
pubspec.yaml

Release 8.0.0

---

CHANGELOG.md
android/build.gradle
android/src/main/kotlin/com/airship/flutter/AirshipPlugin.kt
android/src/main/kotlin/com/airship/flutter/AirshipPluginVersion.kt
ios/Classes/AirshipPluginVersion.swift
ios/Classes/SwiftAirshipPlugin.swift
ios/airship_flutter.podspec
pubspec.yaml

Fixes event stream handling bug that caused deep links from a terminated state to fail in some instances.
Tested deep links from a terminated state on ios and android

Fix event streams on android and ios

---

ios/airship_flutter.podspec

Hi,
Can you please merge this pull request. (It is required when using flutter module)
`s.swift_version = "5.0.0"`
Thank you

fix: add swift version to podspec for flutter module compatibility

---

.github/workflows/release.yml

Updates workflow to allow automatic pub.dev release with an [Open ID Connect token](https://docs.github.com/en/actions/security-for-github-actions/security-hardening-your-deployments/about-security-hardening-with-openid-connect) 
Follows the best practices outlined in [the guide](https://dart.dev/tools/pub/automated-publishing)

Release workflow update

---

android/src/main/kotlin/com/airship/flutter/AirshipPlugin.kt

Fixes the push status method by using resolveDeferred instead of resolveResult so that the coroutine can complete and the serializable status can be sent back.
Also removes a duplicate implementation for feature flags trackInteraction method.
The push status method isn't functioning as it should. The original implementation was returning a coroutine directly through the platform channel which isn't serializable. 
Isolated the issue and reproduced the exception, then making the fix and testing the retrieval flow on launch:
https://gist.github.com/crow/6bdebcb6f04155ca2d3978c9e891db31

Fix areNotificationsAllowed retrieval on Android

---

.pubignore
CHANGELOG.md
android/build.gradle
android/src/main/kotlin/com/airship/flutter/AirshipPlugin.kt
android/src/main/kotlin/com/airship/flutter/AirshipPluginVersion.kt
example/.pubignore
example/ios/Flutter/ephemeral/Packages/FlutterGeneratedPluginSwiftPackage/Package.swift
example/ios/Flutter/ephemeral/Packages/FlutterGeneratedPluginSwiftPackage/Sources/FlutterGeneratedPluginSwiftPackage/FlutterGeneratedPluginSwiftPackage.swift
example/ios/Runner.xcworkspace/xcshareddata/swiftpm/Package.resolved
ios/.pubignore
ios/airship_flutter.podspec
ios/airship_flutter/Package.resolved
ios/airship_flutter/Package.swift
ios/airship_flutter/Sources/airship_flutter/AirshipPlugin.swift
ios/airship_flutter/Sources/airship_flutter/AirshipPluginVersion.swift
lib/src/airship_channel.dart
lib/src/airship_embedded_view.dart
lib/src/attribute_editor.dart
pubspec.yaml

Release 10.3.0
